services:
    sunnerberg_similar_series.helper.tmdb_image_helper:
        class: Sunnerberg\SimilarSeriesBundle\Helper\Image\TmdbImageHelper
        arguments:
            - @tmdb.configuration_repository
            - @cache
    sunnerberg_similar_series.repository.tv_show:
        class: Sunnerberg\SimilarSeriesBundle\Entity\TvShowRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - Sunnerberg\SimilarSeriesBundle\Entity\TvShow
    sunnerberg_similar_series.repository.genre:
        class: Sunnerberg\SimilarSeriesBundle\Entity\GenreRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - Sunnerberg\SimilarSeriesBundle\Entity\Genre
    sunnerberg_similar_series.fetcher.tmdb_show_fetcher:
        class: Sunnerberg\SimilarSeriesBundle\Fetcher\TmdbShowFetcher
        arguments:
            tmdbTvRepository: @tmdb.tv_repository
            tvShowRepository: @sunnerberg_similar_series.repository.tv_show
            genreRepository: @sunnerberg_similar_series.repository.genre
            queueProducer: @old_sound_rabbit_mq.show_patcher_producer
    cache:
        class: Doctrine\Common\Cache\ApcCache
    sunnerberg_similar_series.patcher.show_patcher:
        class: Sunnerberg\SimilarSeriesBundle\Patcher\ShowPatcher
        arguments:
            showFetcher: @sunnerberg_similar_series.fetcher.tmdb_show_fetcher
            showRepository: @sunnerberg_similar_series.repository.tv_show
            entityManager: @doctrine.orm.entity_manager
            logger: @logger
    sunnerberg_similar_series.fetcher.show_fetcher_consumer:
        class: Sunnerberg\SimilarSeriesBundle\Fetcher\ShowFetcherConsumer
        arguments:
            showFetcher: @sunnerberg_similar_series.fetcher.tmdb_show_fetcher
            showRepository: @sunnerberg_similar_series.repository.tv_show
            entityManager: @doctrine.orm.entity_manager
            logger: @logger
    sunnerberg_similar_series.twig.rating_extension:
        class: Sunnerberg\SimilarSeriesBundle\Twig\RatingExtension
        public: false
        tags:
          - { name: twig.extension }
