language: php
php:
  - 5.5
  - 5.6
sudo: false
before_install:
  - pecl install apcu
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
script: phpunit -c app/
