language: php
php:
  - 5.5
  - 5.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php-apc phpunit
  - sudo service apache2 restart
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
script: phpunit -c app/
