security:

    encoders:
        Sunnerberg\SimilarSeriesBundle\Entity\User:
            algorithm: bcrypt

    providers:
        database_provider:
            entity:
                class: Sunnerberg\SimilarSeriesBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login/check

    access_control:
        - { path: ^/user, roles: ROLE_USER }
