security:

    encoders:
        Sunnerberg\SimilarSeriesBundle\Entity\User:
            algorithm: bcrypt

    providers:
        database_provider:
            entity:
                class: Sunnerberg\SimilarSeriesBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        main:
            anonymous: ~
            form_login:
                default_target_path: find
                login_path: /login
                check_path: /login/check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: "%secret%"
                always_remember_me: true

    access_control:
        - { path: ^/user, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/find, roles: IS_AUTHENTICATED_REMEMBERED }
