security:

    encoders:
        Sunnerberg\SimilarSeriesBundle\Entity\User:
            algorithm: bcrypt

    providers:
        database_provider:
            entity:
                class: Sunnerberg\SimilarSeriesBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        default:
            anonymous: ~